 # Pods for CircleCITest
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  platform :ios, '9.0'
 target 'CircleCITest' do
 end
